"""empty message

Revision ID: 35c1fae78dda
Revises: 457dbac85cc0
Create Date: 2025-09-18 23:39:45.742472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c1fae78dda'
down_revision: Union[str, None] = '457dbac85cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categorys', ['category_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categorys', type_='unique')
    # ### end Alembic commands ###
